import type { User, Job } from '@/types'

export const MOCK_PROFESSIONALS: User[] = [
  {
    id: 'pro-1',
    firstName: 'Bright',
    lastName: 'Spark Electrical',
    email: 'brightspark@example.com',
    role: 'vendor',
    city: 'Lagos',
    bio: '15 years experience in residential and commercial electrical work. Fully NEPA certified.',
    skills: ['Repair services', 'Computer operation'],
    rating: 4.9,
    reviewCount: 87,
    isVerified: true,
    createdAt: '2023-01-15T00:00:00Z',
  },
  {
    id: 'pro-2',
    firstName: 'Pipe',
    lastName: 'Masters Nigeria',
    email: 'pipemasters@example.com',
    role: 'vendor',
    city: 'Abuja',
    bio: 'Specialist in pipe installation, burst pipes, and bathroom fittings. Fast response guaranteed.',
    skills: ['Repair services', 'General services'],
    rating: 4.8,
    reviewCount: 64,
    isVerified: true,
    createdAt: '2023-03-10T00:00:00Z',
  },
  {
    id: 'pro-3',
    firstName: 'Cool',
    lastName: 'Breeze AC Services',
    email: 'coolbreeze@example.com',
    role: 'vendor',
    city: 'Lagos',
    bio: 'Expert in all AC brands — Samsung, LG, Daikin. Installation, servicing, and gas refill.',
    skills: ['Repair services', 'Professional services'],
    rating: 4.7,
    reviewCount: 113,
    isVerified: false,
    createdAt: '2022-11-20T00:00:00Z',
  },
  {
    id: 'pro-4',
    firstName: 'Ngozi',
    lastName: 'Eze',
    email: 'ngozi@example.com',
    role: 'vendor',
    city: 'Port Harcourt',
    bio: 'Licensed civil engineer for structural assessments, construction, and drainage systems.',
    skills: ['Environmental services', 'Professional services'],
    rating: 5.0,
    reviewCount: 31,
    isVerified: true,
    createdAt: '2023-06-01T00:00:00Z',
  },
  {
    id: 'pro-5',
    firstName: 'Seun',
    lastName: 'Bello',
    email: 'seun@example.com',
    role: 'vendor',
    city: 'Lagos',
    bio: 'Custom furniture, wardrobes, kitchen cabinets. Quality craftsmanship guaranteed.',
    skills: ['Tradesmen and retailers', 'General services'],
    rating: 4.6,
    reviewCount: 52,
    isVerified: false,
    createdAt: '2023-02-28T00:00:00Z',
  },
  {
    id: 'pro-6',
    firstName: 'Hauwa',
    lastName: 'Danladi',
    email: 'hauwa@example.com',
    role: 'vendor',
    city: 'Kano',
    bio: 'Professional interior and exterior painting. POP ceiling finishing available.',
    skills: ['Repair services', 'Fashion services'],
    rating: 4.8,
    reviewCount: 78,
    isVerified: true,
    createdAt: '2023-04-12T00:00:00Z',
  },
  {
    id: 'pro-7',
    firstName: 'Tech',
    lastName: 'Fix Hub',
    email: 'techfix@example.com',
    role: 'vendor',
    city: 'Lagos',
    bio: 'Phone and laptop repairs, screen replacements, data recovery. Same-day service.',
    skills: ['Repair services', 'Computer operation'],
    rating: 4.5,
    reviewCount: 156,
    isVerified: true,
    createdAt: '2022-08-15T00:00:00Z',
  },
  {
    id: 'pro-8',
    firstName: 'CleanPro',
    lastName: 'Services',
    email: 'cleanpro@example.com',
    role: 'vendor',
    city: 'Abuja',
    bio: 'Professional cleaning services for homes and offices. Eco-friendly products used.',
    skills: ['Cleaning services', 'General services'],
    rating: 4.9,
    reviewCount: 42,
    isVerified: true,
    createdAt: '2023-05-20T00:00:00Z',
  },
]

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-1',
    title: 'Software Engineer',
    description: 'Looking for a skilled software engineer to join our team. Must have experience with web development and modern frameworks.',
    category: 'Software development',
    budget: 250000,
    city: 'Lagos',
    status: 'open',
    timeline: 'urgent',
    posterId: 'client-1',
    posterName: 'Mr Chukwu',
    businessName: 'Asset Matrix',
    businessAddress: '15 Adeola Odeku Street, Victoria Island, Lagos',
    jobType: 'full-time',
    closingDate: '2024-12-31',
    applicationCount: 12,
    createdAt: '2024-07-10T08:00:00Z',
  },
  {
    id: 'job-2',
    title: 'HR Specialist',
    description: 'Seeking an experienced HR Specialist to manage employee relations, recruitment, and training programs.',
    category: 'Professional services',
    budget: 180000,
    city: 'Abuja',
    status: 'open',
    timeline: 'this_week',
    posterId: 'client-2',
    posterName: 'Mrs Bello',
    businessName: 'Etcon Labs',
    businessAddress: '42 Aminu Kano Crescent, Wuse 2, Abuja',
    jobType: 'full-time',
    closingDate: '2024-08-15',
    applicationCount: 8,
    createdAt: '2024-07-09T14:30:00Z',
  },
  {
    id: 'job-3',
    title: 'Laboratory Technician',
    description: 'Looking for a qualified Laboratory Technician to perform tests and maintain laboratory equipment.',
    category: 'Healthcare services',
    budget: 150000,
    city: 'Lagos',
    status: 'open',
    timeline: 'urgent',
    posterId: 'client-3',
    posterName: 'Alhaji Musa',
    businessName: 'Etcon Analytical',
    businessAddress: '8 Adeniran Ogunsanya Street, Surulere, Lagos',
    jobType: 'contract',
    closingDate: '2024-07-25',
    applicationCount: 5,
    createdAt: '2024-07-11T09:00:00Z',
  },
  {
    id: 'job-4',
    title: 'Software Engineer',
    description: 'Senior software engineer needed for backend development and API integration.',
    category: 'Software development',
    budget: 300000,
    city: 'Port Harcourt',
    status: 'open',
    timeline: 'this_week',
    posterId: 'client-4',
    posterName: 'Dr Amadi',
    businessName: 'Asset Matrix',
    businessAddress: '20 Trans Woji Road, Port Harcourt',
    jobType: 'full-time',
    closingDate: '2024-08-01',
    applicationCount: 15,
    createdAt: '2024-07-08T11:00:00Z',
  },
  {
    id: 'job-5',
    title: 'HR Specialist',
    description: 'We need an HR Specialist to handle recruitment and employee wellness programs.',
    category: 'Professional services',
    budget: 160000,
    city: 'Lagos',
    status: 'open',
    timeline: 'this_month',
    posterId: 'client-5',
    posterName: 'Funke A.',
    businessName: 'Etcon Labs',
    businessAddress: '55 Olowu Street, Ikeja, Lagos',
    jobType: 'full-time',
    closingDate: '2024-08-20',
    applicationCount: 6,
    createdAt: '2024-07-07T16:00:00Z',
  },
  {
    id: 'job-6',
    title: 'Laboratory Technician',
    description: 'Join our team as a Laboratory Technician. Experience with analytical instruments required.',
    category: 'Healthcare services',
    budget: 140000,
    city: 'Kano',
    status: 'open',
    timeline: 'urgent',
    posterId: 'client-6',
    posterName: 'Ibrahim T.',
    businessName: 'Etcon Analytical',
    businessAddress: '10 Zaria Road, Kano',
    jobType: 'contract',
    closingDate: '2024-07-30',
    applicationCount: 3,
    createdAt: '2024-07-06T10:00:00Z',
  },
]

const userStore: Array<User & { passwordHash: string }> = []

export function findUserByEmail(email: string) {
  return userStore.find((u) => u.email === email)
}

export function createUser(data: Omit<User, 'id' | 'createdAt'> & { passwordHash: string }) {
  const user = {
    ...data,
    id: `user-${Date.now()}`,
    createdAt: new Date().toISOString(),
  }
  userStore.push(user)
  return user
}