import type { User, Job } from '@/types'

export const MOCK_PROFESSIONALS: User[] = [
  {
    id: 'pro-1',
    firstName: 'Adaeze',
    lastName: 'Okeke',
    email: 'adaeze@example.com',
    role: 'vendor',
    city: 'Lagos',
    bio: '15 years experience in residential and commercial electrical work. Fully NEPA certified.',
    skills: ['Repair services', 'Computer operation'],
    rating: 4.9,
    reviewCount: 87,
    isVerified: true,
    createdAt: '2023-01-15T00:00:00Z',
  },
  {
    id: 'pro-2',
    firstName: 'Kola',
    lastName: 'Musa',
    email: 'kola@example.com',
    role: 'vendor',
    city: 'Abuja',
    bio: 'Specialist in pipe installation, burst pipes, and bathroom fittings. Fast response guaranteed.',
    skills: ['Repair services', 'General services'],
    rating: 4.8,
    reviewCount: 64,
    isVerified: true,
    createdAt: '2023-03-10T00:00:00Z',
  },
  {
    id: 'pro-3',
    firstName: 'Tunde',
    lastName: 'James',
    email: 'tunde@example.com',
    role: 'vendor',
    city: 'Lagos',
    bio: 'Expert in all AC brands — Samsung, LG, Daikin. Installation, servicing, and gas refill.',
    skills: ['Repair services', 'Professional services'],
    rating: 4.7,
    reviewCount: 113,
    isVerified: false,
    createdAt: '2022-11-20T00:00:00Z',
  },
  {
    id: 'pro-4',
    firstName: 'Ngozi',
    lastName: 'Eze',
    email: 'ngozi@example.com',
    role: 'vendor',
    city: 'Port Harcourt',
    bio: 'Licensed civil engineer for structural assessments, construction, and drainage systems.',
    skills: ['Environmental services', 'Professional services'],
    rating: 5.0,
    reviewCount: 31,
    isVerified: true,
    createdAt: '2023-06-01T00:00:00Z',
  },
  {
    id: 'pro-5',
    firstName: 'Seun',
    lastName: 'Bello',
    email: 'seun@example.com',
    role: 'vendor',
    city: 'Lagos',
    bio: 'Custom furniture, wardrobes, kitchen cabinets. Quality craftsmanship guaranteed.',
    skills: ['Tradesmen and retailers', 'General services'],
    rating: 4.6,
    reviewCount: 52,
    isVerified: false,
    createdAt: '2023-02-28T00:00:00Z',
  },
  {
    id: 'pro-6',
    firstName: 'Hauwa',
    lastName: 'Danladi',
    email: 'hauwa@example.com',
    role: 'vendor',
    city: 'Kano',
    bio: 'Professional interior and exterior painting. POP ceiling finishing available.',
    skills: ['Repair services', 'Fashion services'],
    rating: 4.8,
    reviewCount: 78,
    isVerified: true,
    createdAt: '2023-04-12T00:00:00Z',
  },
]

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-1',
    title: 'Electrical wiring for 3-bedroom flat',
    description: 'Need complete rewiring of a 3-bedroom flat in Lekki Phase 1. Must be NEPA certified. Work to start ASAP.',
    category: 'Repair services',
    budget: 120000,
    city: 'Lagos',
    status: 'open',
    timeline: 'urgent',
    posterId: 'client-1',
    posterName: 'Mr Chukwu',
    applicationCount: 4,
    createdAt: '2024-07-10T08:00:00Z',
  },
  {
    id: 'job-2',
    title: 'Professional cleaning for office space',
    description: 'Need a complete office cleaning service for a 5-room office space in Wuse 2 Abuja.',
    category: 'Cleaning services',
    budget: 35000,
    city: 'Abuja',
    status: 'open',
    timeline: 'this_week',
    posterId: 'client-2',
    posterName: 'Mrs Bello',
    applicationCount: 7,
    createdAt: '2024-07-09T14:30:00Z',
  },
  {
    id: 'job-3',
    title: 'Event photography for birthday party',
    description: 'Looking for a professional photographer for a 50th birthday celebration in Surulere.',
    category: 'Events and rentals',
    budget: 80000,
    city: 'Lagos',
    status: 'open',
    timeline: 'urgent',
    posterId: 'client-3',
    posterName: 'Alhaji Musa',
    applicationCount: 2,
    createdAt: '2024-07-11T09:00:00Z',
  },
  {
    id: 'job-4',
    title: 'Logo design for new business',
    description: 'Need a modern logo design for a new restaurant brand.',
    category: 'Software development',
    budget: 50000,
    city: 'Port Harcourt',
    status: 'open',
    timeline: 'this_week',
    posterId: 'client-4',
    posterName: 'Dr Amadi',
    applicationCount: 3,
    createdAt: '2024-07-08T11:00:00Z',
  },
  {
    id: 'job-5',
    title: 'Catering for corporate event',
    description: 'Need a catering service for 50 people for a corporate meeting.',
    category: 'Restaurant and lounges',
    budget: 150000,
    city: 'Lagos',
    status: 'open',
    timeline: 'this_month',
    posterId: 'client-5',
    posterName: 'Funke A.',
    applicationCount: 6,
    createdAt: '2024-07-07T16:00:00Z',
  },
  {
    id: 'job-6',
    title: 'Hair and makeup for wedding',
    description: 'Looking for a professional hair and makeup artist for a bride on her wedding day.',
    category: 'Spa and beauty parlour',
    budget: 75000,
    city: 'Kano',
    status: 'open',
    timeline: 'urgent',
    posterId: 'client-6',
    posterName: 'Ibrahim T.',
    applicationCount: 5,
    createdAt: '2024-07-06T10:00:00Z',
  },
]

const userStore: Array<User & { passwordHash: string }> = []

export function findUserByEmail(email: string) {
  return userStore.find((u) => u.email === email)
}

export function createUser(data: Omit<User, 'id' | 'createdAt'> & { passwordHash: string }) {
  const user = {
    ...data,
    id: `user-${Date.now()}`,
    createdAt: new Date().toISOString(),
  }
  userStore.push(user)
  return user
}